server.port: 7003
server.error.include-message: always
spring.application.name: review
app.eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
logging:
  level:
    root: INFO
    com.vidhan: DEBUG
---
spring.config.activate.on-profile: docker
app.eureka-server: eureka
server.port: 8080